import { Geist, Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

const roboto= Roboto({ 
  subsets:['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={roboto.className}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        <Navbar/>
         <div className="flex mx-auto max-w-7xl">
          {children}
         </div>
        </body>
    </html>
  );
}

//default routes.
export const Metadata = {
  title:{
    default:'revalidate and metadata',
  }
}
